"""add_equipment_tables

Revision ID: 970f3a9f8211
Revises: b3691636e3ac
Create Date: 2025-07-28 15:02:55.499514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970f3a9f8211'
down_revision: Union[str, None] = 'b3691636e3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create equipment table
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=True, comment='设备编码'),
    sa.Column('equipment_name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('equipment_type', sa.Enum('PRODUCTION', 'TESTING', 'TRANSPORT', 'AUXILIARY', 'SAFETY', name='equipmenttype'), nullable=False, comment='设备类型'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='设备型号'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='制造商'),
    sa.Column('serial_number', sa.String(length=100), nullable=True, comment='序列号'),
    sa.Column('purchase_date', sa.DateTime(), nullable=True, comment='采购日期'),
    sa.Column('installation_date', sa.DateTime(), nullable=True, comment='安装日期'),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True, comment='保修到期日'),
    sa.Column('specifications', sa.Text(), nullable=True, comment='技术规格（JSON格式）'),
    sa.Column('capacity', sa.Float(), nullable=True, comment='产能'),
    sa.Column('power_consumption', sa.Float(), nullable=True, comment='功耗（kW）'),
    sa.Column('operating_temperature', sa.String(length=50), nullable=True, comment='工作温度范围'),
    sa.Column('operating_pressure', sa.String(length=50), nullable=True, comment='工作压力范围'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='设备位置'),
    sa.Column('workshop', sa.String(length=100), nullable=True, comment='车间'),
    sa.Column('production_line', sa.String(length=100), nullable=True, comment='生产线'),
    sa.Column('status', sa.Enum('RUNNING', 'IDLE', 'MAINTENANCE', 'BREAKDOWN', 'OFFLINE', 'RETIRED', name='equipmentstatus'), nullable=True, comment='设备状态'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('total_runtime', sa.Float(), nullable=True, comment='总运行时间（小时）'),
    sa.Column('total_downtime', sa.Float(), nullable=True, comment='总停机时间（小时）'),
    sa.Column('total_maintenance_time', sa.Float(), nullable=True, comment='总维护时间（小时）'),
    sa.Column('availability_rate', sa.Float(), nullable=True, comment='可用率'),
    sa.Column('purchase_cost', sa.Float(), nullable=True, comment='采购成本'),
    sa.Column('installation_cost', sa.Float(), nullable=True, comment='安装成本'),
    sa.Column('annual_maintenance_cost', sa.Float(), nullable=True, comment='年维护成本'),
    sa.Column('depreciation_rate', sa.Float(), nullable=True, comment='折旧率'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('maintainer_id', sa.Integer(), nullable=True, comment='维护员ID'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='设备管理员ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('description', sa.Text(), nullable=True, comment='设备描述'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    
    # Create maintenance_records table
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_number', sa.String(length=50), nullable=True, comment='维护单号'),
    sa.Column('equipment_id', sa.Integer(), nullable=False, comment='设备ID'),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'ROUTINE', 'OVERHAUL', name='maintenancetype'), nullable=False, comment='维护类型'),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='maintenancestatus'), nullable=True, comment='维护状态'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='优先级'),
    sa.Column('planned_start_time', sa.DateTime(), nullable=False, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(), nullable=True, comment='计划结束时间'),
    sa.Column('planned_duration', sa.Float(), nullable=True, comment='计划持续时间（小时）'),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True, comment='实际结束时间'),
    sa.Column('actual_duration', sa.Float(), nullable=True, comment='实际持续时间（小时）'),
    sa.Column('maintenance_items', sa.Text(), nullable=True, comment='维护项目（JSON格式）'),
    sa.Column('maintenance_description', sa.Text(), nullable=True, comment='维护描述'),
    sa.Column('parts_replaced', sa.Text(), nullable=True, comment='更换部件（JSON格式）'),
    sa.Column('materials_used', sa.Text(), nullable=True, comment='使用材料（JSON格式）'),
    sa.Column('maintenance_result', sa.Text(), nullable=True, comment='维护结果'),
    sa.Column('issues_found', sa.Text(), nullable=True, comment='发现问题'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='建议'),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True, comment='下次维护日期'),
    sa.Column('labor_cost', sa.Float(), nullable=True, comment='人工成本'),
    sa.Column('parts_cost', sa.Float(), nullable=True, comment='配件成本'),
    sa.Column('material_cost', sa.Float(), nullable=True, comment='材料成本'),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='总成本'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='分配给'),
    sa.Column('performed_by', sa.Integer(), nullable=True, comment='执行人'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='批准人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_number'), 'maintenance_records', ['maintenance_number'], unique=True)
    
    # Create equipment_operation_logs table
    op.create_table('equipment_operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False, comment='设备ID'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('operation_description', sa.Text(), nullable=True, comment='操作描述'),
    sa.Column('previous_status', sa.String(length=50), nullable=True, comment='之前状态'),
    sa.Column('new_status', sa.String(length=50), nullable=True, comment='新状态'),
    sa.Column('operating_parameters', sa.Text(), nullable=True, comment='运行参数（JSON格式）'),
    sa.Column('performance_metrics', sa.Text(), nullable=True, comment='性能指标（JSON格式）'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_operation_logs_id'), 'equipment_operation_logs', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_operation_logs_id'), table_name='equipment_operation_logs')
    op.drop_table('equipment_operation_logs')
    op.drop_index(op.f('ix_maintenance_records_maintenance_number'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###