"""add reminder system tables

Revision ID: b3691636e3ac
Revises: 
Create Date: 2025-07-27 09:59:02.100665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3691636e3ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_code', sa.String(length=50), nullable=False, comment='BOM编码'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('product_model', sa.String(length=50), nullable=True, comment='产品型号'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('effective_date', sa.DateTime(), nullable=True, comment='生效日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='失效日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_bom_code'), 'bom', ['bom_code'], unique=True)
    op.create_index(op.f('ix_bom_id'), 'bom', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('category', sa.Enum('RAW_MATERIAL', 'SEMI_FINISHED', 'FINISHED_PRODUCT', 'STANDARD_PART', 'CONSUMABLE', 'TOOL', name='materialcategory'), nullable=False, comment='物料类别'),
    sa.Column('current_stock', sa.Float(), nullable=True, comment='当前库存'),
    sa.Column('safety_stock', sa.Float(), nullable=True, comment='安全库存'),
    sa.Column('max_stock', sa.Float(), nullable=True, comment='最大库存'),
    sa.Column('location', sa.String(length=50), nullable=True, comment='存储位置'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('last_purchase_price', sa.Float(), nullable=True, comment='最近采购价'),
    sa.Column('average_price', sa.Float(), nullable=True, comment='平均价格'),
    sa.Column('primary_supplier', sa.String(length=100), nullable=True, comment='主要供应商'),
    sa.Column('backup_suppliers', sa.Text(), nullable=True, comment='备用供应商'),
    sa.Column('technical_specs', sa.Text(), nullable=True, comment='技术规格'),
    sa.Column('quality_standards', sa.Text(), nullable=True, comment='质量标准'),
    sa.Column('storage_conditions', sa.Text(), nullable=True, comment='存储条件'),
    sa.Column('status', sa.Enum('ACTIVE', 'NORMAL', 'WARNING', 'OUT_OF_STOCK', 'OVERSTOCKED', 'DISCONTINUED', name='materialstatus'), nullable=True, comment='物料状态'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('total_in', sa.Float(), nullable=True, comment='累计入库'),
    sa.Column('total_out', sa.Float(), nullable=True, comment='累计出库'),
    sa.Column('turnover_rate', sa.Float(), nullable=True, comment='周转率'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单编号'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户名称'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('product_model', sa.String(length=50), nullable=True, comment='产品型号'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='总金额'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='下单日期'),
    sa.Column('delivery_date', sa.DateTime(), nullable=False, comment='交货日期'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=True, comment='订单状态'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='orderpriority'), nullable=True, comment='优先级'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('delivery_address', sa.Text(), nullable=True, comment='交货地址'),
    sa.Column('technical_requirements', sa.Text(), nullable=True, comment='技术要求'),
    sa.Column('quality_standards', sa.Text(), nullable=True, comment='质量标准'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=50), nullable=False, comment='采购单号'),
    sa.Column('supplier_name', sa.String(length=100), nullable=False, comment='供应商名称'),
    sa.Column('supplier_contact', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('supplier_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('supplier_address', sa.Text(), nullable=True, comment='供应商地址'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='下单日期'),
    sa.Column('expected_date', sa.DateTime(), nullable=False, comment='期望到货日期'),
    sa.Column('actual_date', sa.DateTime(), nullable=True, comment='实际到货日期'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='订单总金额'),
    sa.Column('paid_amount', sa.Float(), nullable=True, comment='已付金额'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'ORDERED', 'RECEIVED', 'COMPLETED', 'CANCELLED', name='purchasestatus'), nullable=True, comment='采购状态'),
    sa.Column('applicant', sa.String(length=50), nullable=True, comment='申请人'),
    sa.Column('approver', sa.String(length=50), nullable=True, comment='审批人'),
    sa.Column('approval_date', sa.DateTime(), nullable=True, comment='审批日期'),
    sa.Column('approval_remark', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=True)
    op.create_table('user_login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
    sa.Column('logout_time', sa.DateTime(), nullable=True, comment='登出时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='在线时长(分钟)'),
    sa.Column('login_result', sa.String(length=20), nullable=False, comment='登录结果'),
    sa.Column('failure_reason', sa.String(length=100), nullable=True, comment='失败原因'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'),
    sa.Column('os', sa.String(length=100), nullable=True, comment='操作系统'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='登录地点'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_logs_id'), 'user_login_logs', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='会话ID'),
    sa.Column('token', sa.String(length=500), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='刷新令牌'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
    sa.Column('last_activity', sa.DateTime(), nullable=True, comment='最后活动时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'),
    sa.Column('os', sa.String(length=100), nullable=True, comment='操作系统'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('logout_time', sa.DateTime(), nullable=True, comment='登出时间'),
    sa.Column('logout_reason', sa.String(length=100), nullable=True, comment='登出原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True, comment='密码修改时间'),
    sa.Column('password_expires_at', sa.DateTime(), nullable=True, comment='密码过期时间'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'SUPERVISOR', 'OPERATOR', 'VIEWER', name='userrole'), nullable=True, comment='角色'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表(JSON)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'LOCKED', name='userstatus'), nullable=True, comment='状态'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级用户'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('login_count', sa.Integer(), nullable=True, comment='登录次数'),
    sa.Column('failed_login_count', sa.Integer(), nullable=True, comment='失败登录次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='锁定到期时间'),
    sa.Column('workshop', sa.String(length=100), nullable=True, comment='所属车间'),
    sa.Column('team', sa.String(length=100), nullable=True, comment='所属班组'),
    sa.Column('supervisor_id', sa.Integer(), nullable=True, comment='上级主管ID'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True, comment='紧急联系人'),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True, comment='紧急联系电话'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言'),
    sa.Column('theme', sa.String(length=20), nullable=True, comment='主题'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False, comment='BOM ID'),
    sa.Column('material_id', sa.Integer(), nullable=False, comment='物料ID'),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='用量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('loss_rate', sa.Float(), nullable=True, comment='损耗率(%)'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级'),
    sa.Column('parent_item_id', sa.Integer(), nullable=True, comment='父级明细ID'),
    sa.Column('is_substitute', sa.Boolean(), nullable=True, comment='是否替代料'),
    sa.Column('substitute_group', sa.String(length=50), nullable=True, comment='替代组'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['bom_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_items_id'), 'bom_items', ['id'], unique=False)
    op.create_table('production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_no', sa.String(length=50), nullable=False, comment='计划编号'),
    sa.Column('plan_name', sa.String(length=100), nullable=False, comment='计划名称'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='关联订单ID'),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='订单编号'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('product_model', sa.String(length=50), nullable=True, comment='产品型号'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='计划数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('plan_start_date', sa.DateTime(), nullable=False, comment='计划开始日期'),
    sa.Column('plan_end_date', sa.DateTime(), nullable=False, comment='计划完成日期'),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际完成日期'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'PAUSED', name='planstatus'), nullable=True, comment='计划状态'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='planpriority'), nullable=True, comment='优先级'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成进度(%)'),
    sa.Column('workshop', sa.String(length=50), nullable=True, comment='生产车间'),
    sa.Column('production_line', sa.String(length=50), nullable=True, comment='生产线'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('team_members', sa.Text(), nullable=True, comment='团队成员'),
    sa.Column('process_flow', sa.Text(), nullable=True, comment='工艺流程'),
    sa.Column('technical_requirements', sa.Text(), nullable=True, comment='技术要求'),
    sa.Column('quality_standards', sa.Text(), nullable=True, comment='质量标准'),
    sa.Column('material_cost', sa.Float(), nullable=True, comment='材料成本'),
    sa.Column('labor_cost', sa.Float(), nullable=True, comment='人工成本'),
    sa.Column('equipment_cost', sa.Float(), nullable=True, comment='设备成本'),
    sa.Column('other_cost', sa.Float(), nullable=True, comment='其他成本'),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='总成本'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_plans_id'), 'production_plans', ['id'], unique=False)
    op.create_index(op.f('ix_production_plans_plan_no'), 'production_plans', ['plan_no'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False, comment='采购订单ID'),
    sa.Column('material_id', sa.Integer(), nullable=False, comment='物料ID'),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='规格'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='采购数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='总价'),
    sa.Column('received_quantity', sa.Float(), nullable=True, comment='已收货数量'),
    sa.Column('remaining_quantity', sa.Float(), nullable=True, comment='剩余数量'),
    sa.Column('quality_requirement', sa.Text(), nullable=True, comment='质量要求'),
    sa.Column('inspection_result', sa.String(length=50), nullable=True, comment='检验结果'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('reminder_rules',
    sa.Column('id', sa.Integer(), nullable=False, comment='规则ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('reminder_type', sa.Enum('ORDER_DUE', 'TASK_OVERDUE', 'QUALITY_ISSUE', 'EQUIPMENT_MAINTENANCE', 'MATERIAL_SHORTAGE', 'CUSTOM', name='remindertype'), nullable=False, comment='催办类型'),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False, comment='触发条件'),
    sa.Column('initial_level', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reminderlevel'), nullable=True, comment='初始级别'),
    sa.Column('escalation_intervals', sa.JSON(), nullable=True, comment='升级间隔配置'),
    sa.Column('max_escalations', sa.Integer(), nullable=True, comment='最大升级次数'),
    sa.Column('recipient_config', sa.JSON(), nullable=False, comment='接收者配置'),
    sa.Column('title_template', sa.String(length=200), nullable=False, comment='标题模板'),
    sa.Column('content_template', sa.Text(), nullable=False, comment='内容模板'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_rules_id'), 'reminder_rules', ['id'], unique=False)
    op.create_table('production_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_no', sa.String(length=50), nullable=False, comment='阶段编号'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='阶段名称'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='生产计划ID'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='阶段顺序'),
    sa.Column('description', sa.Text(), nullable=True, comment='阶段描述'),
    sa.Column('plan_start_date', sa.DateTime(), nullable=False, comment='计划开始日期'),
    sa.Column('plan_end_date', sa.DateTime(), nullable=False, comment='计划完成日期'),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际完成日期'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'PAUSED', name='planstatus'), nullable=True, comment='阶段状态'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成进度(%)'),
    sa.Column('workshop', sa.String(length=50), nullable=True, comment='执行车间'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('required_skills', sa.Text(), nullable=True, comment='所需技能'),
    sa.Column('quality_checkpoints', sa.Text(), nullable=True, comment='质量检查点'),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True, comment='验收标准'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_stages_id'), 'production_stages', ['id'], unique=False)
    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_no', sa.String(length=50), nullable=False, comment='跟踪编号'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='订单ID'),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单编号'),
    sa.Column('plan_id', sa.Integer(), nullable=True, comment='生产计划ID'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('product_model', sa.String(length=50), nullable=True, comment='产品型号'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('plan_start_date', sa.DateTime(), nullable=False, comment='计划开始日期'),
    sa.Column('plan_end_date', sa.DateTime(), nullable=False, comment='计划完成日期'),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际完成日期'),
    sa.Column('current_stage', sa.String(length=50), nullable=True, comment='当前阶段'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成进度(%)'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'PAUSED', 'CANCELLED', name='progressstatus'), nullable=True, comment='状态'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('workshop', sa.String(length=50), nullable=True, comment='车间'),
    sa.Column('team_members', sa.Text(), nullable=True, comment='团队成员'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='优先级'),
    sa.Column('issues', sa.Text(), nullable=True, comment='存在问题'),
    sa.Column('risks', sa.Text(), nullable=True, comment='风险点'),
    sa.Column('solutions', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_id'), 'progress_records', ['id'], unique=False)
    op.create_index(op.f('ix_progress_records_record_no'), 'progress_records', ['record_no'], unique=True)
    op.create_table('reminder_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='催办记录ID'),
    sa.Column('reminder_type', sa.Enum('ORDER_DUE', 'TASK_OVERDUE', 'QUALITY_ISSUE', 'EQUIPMENT_MAINTENANCE', 'MATERIAL_SHORTAGE', 'CUSTOM', name='remindertype'), nullable=False, comment='催办类型'),
    sa.Column('level', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reminderlevel'), nullable=True, comment='催办级别'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'RESPONDED', 'ESCALATED', 'CANCELLED', name='reminderstatus'), nullable=True, comment='催办状态'),
    sa.Column('related_type', sa.String(length=50), nullable=False, comment='关联对象类型'),
    sa.Column('related_id', sa.Integer(), nullable=False, comment='关联对象ID'),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False, comment='接收者用户ID'),
    sa.Column('sender_user_id', sa.Integer(), nullable=True, comment='发送者用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='催办标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='催办内容'),
    sa.Column('data', sa.JSON(), nullable=True, comment='催办相关数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('response_time', sa.DateTime(), nullable=True, comment='响应时间'),
    sa.Column('escalation_time', sa.DateTime(), nullable=True, comment='升级时间'),
    sa.Column('is_responded', sa.Boolean(), nullable=True, comment='是否已响应'),
    sa.Column('is_escalated', sa.Boolean(), nullable=True, comment='是否已升级'),
    sa.Column('escalation_count', sa.Integer(), nullable=True, comment='升级次数'),
    sa.Column('rule_id', sa.Integer(), nullable=True, comment='关联规则ID'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rules.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_records_id'), 'reminder_records', ['id'], unique=False)
    op.create_table('reminder_responses',
    sa.Column('id', sa.Integer(), nullable=False, comment='响应ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='催办记录ID'),
    sa.Column('responder_id', sa.Integer(), nullable=False, comment='响应者ID'),
    sa.Column('response_type', sa.String(length=50), nullable=False, comment='响应类型'),
    sa.Column('response_content', sa.Text(), nullable=True, comment='响应内容'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据'),
    sa.Column('response_time', sa.DateTime(), nullable=True, comment='响应时间'),
    sa.Column('is_resolved', sa.Boolean(), nullable=True, comment='是否已解决'),
    sa.Column('resolution_note', sa.Text(), nullable=True, comment='解决说明'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder_records.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_responses_id'), 'reminder_responses', ['id'], unique=False)
    op.create_table('stage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_no', sa.String(length=50), nullable=False, comment='阶段编号'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='阶段名称'),
    sa.Column('progress_id', sa.Integer(), nullable=False, comment='进度记录ID'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='阶段顺序'),
    sa.Column('description', sa.Text(), nullable=True, comment='阶段描述'),
    sa.Column('plan_start_date', sa.DateTime(), nullable=False, comment='计划开始日期'),
    sa.Column('plan_end_date', sa.DateTime(), nullable=False, comment='计划完成日期'),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际完成日期'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='持续时间(天)'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成进度(%)'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'PAUSED', 'CANCELLED', name='progressstatus'), nullable=True, comment='状态'),
    sa.Column('responsible_person', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('workshop', sa.String(length=50), nullable=True, comment='执行车间'),
    sa.Column('equipment', sa.String(length=100), nullable=True, comment='使用设备'),
    sa.Column('process_requirements', sa.Text(), nullable=True, comment='工艺要求'),
    sa.Column('quality_checkpoints', sa.Text(), nullable=True, comment='质量检查点'),
    sa.Column('material_consumption', sa.Text(), nullable=True, comment='物料消耗'),
    sa.Column('labor_hours', sa.Float(), nullable=True, comment='工时'),
    sa.Column('equipment_hours', sa.Float(), nullable=True, comment='设备工时'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='质量评分'),
    sa.Column('defect_count', sa.Integer(), nullable=True, comment='缺陷数量'),
    sa.Column('rework_count', sa.Integer(), nullable=True, comment='返工次数'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['progress_id'], ['progress_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_records_id'), 'stage_records', ['id'], unique=False)
    op.create_table('progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False, comment='进度记录ID'),
    sa.Column('stage_id', sa.Integer(), nullable=True, comment='阶段记录ID'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日期'),
    sa.Column('update_type', sa.String(length=50), nullable=True, comment='更新类型'),
    sa.Column('previous_progress', sa.Integer(), nullable=True, comment='之前进度(%)'),
    sa.Column('current_progress', sa.Integer(), nullable=True, comment='当前进度(%)'),
    sa.Column('progress_change', sa.Integer(), nullable=True, comment='进度变化(%)'),
    sa.Column('previous_status', sa.String(length=50), nullable=True, comment='之前状态'),
    sa.Column('current_status', sa.String(length=50), nullable=True, comment='当前状态'),
    sa.Column('update_content', sa.Text(), nullable=True, comment='更新内容'),
    sa.Column('achievements', sa.Text(), nullable=True, comment='完成工作'),
    sa.Column('next_plans', sa.Text(), nullable=True, comment='下步计划'),
    sa.Column('issues_found', sa.Text(), nullable=True, comment='发现问题'),
    sa.Column('risks_identified', sa.Text(), nullable=True, comment='识别风险'),
    sa.Column('mitigation_actions', sa.Text(), nullable=True, comment='缓解措施'),
    sa.Column('resources_used', sa.Text(), nullable=True, comment='资源使用'),
    sa.Column('time_spent', sa.Float(), nullable=True, comment='耗时(小时)'),
    sa.Column('cost_incurred', sa.Float(), nullable=True, comment='发生成本'),
    sa.Column('updated_by', sa.String(length=50), nullable=False, comment='更新人'),
    sa.Column('reviewer', sa.String(length=50), nullable=True, comment='审核人'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['progress_id'], ['progress_records.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_updates_id'), 'progress_updates', ['id'], unique=False)
    op.create_table('quality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_no', sa.String(length=50), nullable=False, comment='检查编号'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='订单ID'),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单编号'),
    sa.Column('stage_id', sa.Integer(), nullable=True, comment='阶段ID'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='检查阶段'),
    sa.Column('check_date', sa.DateTime(), nullable=False, comment='检查日期'),
    sa.Column('check_type', sa.String(length=50), nullable=True, comment='检查类型'),
    sa.Column('check_items', sa.Text(), nullable=True, comment='检查项目'),
    sa.Column('check_standards', sa.Text(), nullable=True, comment='检查标准'),
    sa.Column('check_result', sa.Enum('PASS', 'FAIL', 'REWORK', 'PENDING', name='qualityresult'), nullable=False, comment='检查结果'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='质量评分'),
    sa.Column('pass_rate', sa.Float(), nullable=True, comment='合格率(%)'),
    sa.Column('defect_count', sa.Integer(), nullable=True, comment='缺陷数量'),
    sa.Column('defect_types', sa.Text(), nullable=True, comment='缺陷类型'),
    sa.Column('defect_description', sa.Text(), nullable=True, comment='缺陷描述'),
    sa.Column('defect_images', sa.Text(), nullable=True, comment='缺陷图片'),
    sa.Column('corrective_actions', sa.Text(), nullable=True, comment='纠正措施'),
    sa.Column('preventive_actions', sa.Text(), nullable=True, comment='预防措施'),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True, comment='是否需要跟进'),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True, comment='跟进日期'),
    sa.Column('inspector', sa.String(length=50), nullable=False, comment='检验员'),
    sa.Column('reviewer', sa.String(length=50), nullable=True, comment='复核人'),
    sa.Column('approver', sa.String(length=50), nullable=True, comment='批准人'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_records_check_no'), 'quality_records', ['check_no'], unique=True)
    op.create_index(op.f('ix_quality_records_id'), 'quality_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_records_id'), table_name='quality_records')
    op.drop_index(op.f('ix_quality_records_check_no'), table_name='quality_records')
    op.drop_table('quality_records')
    op.drop_index(op.f('ix_progress_updates_id'), table_name='progress_updates')
    op.drop_table('progress_updates')
    op.drop_index(op.f('ix_stage_records_id'), table_name='stage_records')
    op.drop_table('stage_records')
    op.drop_index(op.f('ix_reminder_responses_id'), table_name='reminder_responses')
    op.drop_table('reminder_responses')
    op.drop_index(op.f('ix_reminder_records_id'), table_name='reminder_records')
    op.drop_table('reminder_records')
    op.drop_index(op.f('ix_progress_records_record_no'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_production_stages_id'), table_name='production_stages')
    op.drop_table('production_stages')
    op.drop_index(op.f('ix_reminder_rules_id'), table_name='reminder_rules')
    op.drop_table('reminder_rules')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_production_plans_plan_no'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_id'), table_name='production_plans')
    op.drop_table('production_plans')
    op.drop_index(op.f('ix_bom_items_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_login_logs_id'), table_name='user_login_logs')
    op.drop_table('user_login_logs')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_bom_id'), table_name='bom')
    op.drop_index(op.f('ix_bom_bom_code'), table_name='bom')
    op.drop_table('bom')
    # ### end Alembic commands ###
