app:
  api_port: 8000
  api_url: http://localhost:8000/api
  name: PG-PMC
  port: 3000
  url: http://localhost:3000
backup_dir: s:/PG-PMC/bak
compliance:
  enforce_checks: true
  monitoring:
    check_interval: 300
    enabled: true
    log_violations: true
  pre_operation_check:
    enabled: true
    script_path: tools/pre_operation_check.py
  violation_handling:
    block_operation: true
    log_level: ERROR
    require_approval: true
config_version: 1.0.0
created_at: '2025-07-26T23:06:29.517000'
database:
  dev_name: PG-PMC_dev_db
  host: localhost
  name: pgdev_db
  password: password
  port: 5432
  test_name: PG-PMC_test_db
  url_template: postgresql://{username}:{password}@{host}:{port}/{database_name}
  username: postgres
environment:
  app:
    api_port: 8000
    api_url: http://localhost:8000
    name: 3AI电器实业有限公司
    port: 3000
    url: http://localhost:3000
    version: 1.0.0
  cache:
    max_items: 1000
    static_max_age: 31536000
    ttl: 3600
  database:
    host: localhost
    name: PG-PMC_db
    password: password
    pool_idle_timeout: 30000
    pool_max: 10
    pool_min: 2
    port: 5432
    test_url: postgresql://postgres:password@localhost:5432/PG-PMC_test_db
    url: postgresql://postgres:password@localhost:5432/PG-PMC_db
    user: postgres
  development:
    api_docs_enabled: true
    api_docs_path: /docs
    debug: true
    debug_mode: true
    log_level: DEBUG
    verbose_logging: false
    webpack_dev_server_host: localhost
    webpack_dev_server_port: 3000
    webpack_hot_reload: true
  external_services:
    openai_api_key: your-openai-api-key
    openai_max_tokens: 2000
    openai_model: gpt-4
  mail:
    from_address: noreply@pingao.com
    from_name: 3AI电器实业有限公司
    smtp_host: smtp.gmail.com
    smtp_pass: your-app-password
    smtp_port: 587
    smtp_secure: false
    smtp_user: your-email@gmail.com
  monitoring:
    health_check_endpoint: /health
    health_check_interval: 30000
  network:
    default_ports:
      api: 8000
      dev_server: 3000
      frontend: 3000
      preview: 3000
    host: localhost
    preview_host: localhost
  production:
    debug: false
    log_level: INFO
  rate_limit:
    max_requests: 100
    upload_limit: 10
    window_ms: 900000
  redis:
    db: 0
    host: localhost
    password: ''
    port: 6379
    session_db: 1
    url: redis://localhost:6379/0
  security:
    cors_credentials: true
    cors_origin: http://localhost:3000
    encryption_key: your-32-character-encryption-key
    jwt_expires_in: 7d
    jwt_refresh_expires_in: 30d
    jwt_secret: your-super-secret-jwt-key-change-this-in-production
    session_max_age: 86400000
    session_secret: your-session-secret-key-change-this
  storage:
    allowed_file_types: jpg,jpeg,png,gif,pdf,doc,docx,txt
    max_file_size: 10485760
    upload_dir: ./uploads
  test:
    coverage_threshold: 80
    debug: true
    log_level: DEBUG
    timeout: 30000
file_types:
  allowed_extensions:
  - .py
  - .js
  - .ts
  - .jsx
  - .tsx
  - .md
  - .txt
  - .json
  - .yaml
  - .yml
  - .html
  - .css
  - .scss
  - .less
  - .sql
  - .sh
  - .bat
  - .ps1
  encoding: utf-8
  exclude_patterns:
  - '*.pyc'
  - '*.pyo'
  - '*.pyd'
  - __pycache__
  - node_modules
  - .git
  - '*.log'
  - '*.tmp'
  line_ending: auto
  max_file_size: 10485760
git:
  auto_push: true
  commit_message_prefix: 自动备份
  default_branch: main
  repo_dir_name: github_repo
logging:
  backup_count: 30
  compress: true
  date_pattern: YYYY-MM-DD
  dir: ./logs
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: info
  max_files: 5
  max_size: 10m
  rotation: daily
mcp:
  github:
    enabled: true
    isolation_mode: global
    tools:
    - create_repository
    - create_or_update_file
    - push_files
    - get_repository
    - list_repositories
    - create_branch
    - create_pull_request
    - get_file_contents
    - delete_file
    - search_repositories
  memory:
    isolation_mode: project
    storage_path: docs/02-开发/memory.json
  task_manager:
    isolation_mode: project
    storage_path: docs/02-开发/tasks.json
migration:
  cleanup_dirs:
  - __pycache__
  - node_modules
  - .git
  - logs
  - bak
  reset_files:
  - .env
  - docs/02-开发/开发日志.md
  - docs/02-开发/tasks.json
  update_patterns:
  - '*.md'
  - '*.yaml'
  - '*.yml'
  - '*.json'
  - '*.js'
  - '*.py'
  - '*.sh'
  - .env*
paths:
  backup_dir: s:/PG-PMC/bak
  docs_dir: s:/PG-PMC/docs
  logs_dir: s:/PG-PMC/logs
  project_dir: s:/PG-PMC/project
  required_dirs:
  - src
  - logs
  - bak
  - docs
  - tools
  - project
  required_files:
  - README.md
  - requirements.txt
  root: s:/PG-PMC
  tools_dir: s:/PG-PMC/tools
performance:
  cache_size: 100
  connection_pool_size: 10
  cpu_limit: 1000m
  enable_compression: true
  max_concurrent_requests: 100
  memory_limit: 512MB
  request_timeout: 30000
  static_cache_ttl: 86400
  worker_processes: 4
project:
  created_at: '2025-07-26T23:06:29.517000'
  name: PG-PMC
  root: s:/PG-PMC
  updated_at: '2025-07-26T23:06:29.517000'
project_description: 3AI电器实业有限公司研发管理项目
project_name: PG-PMC
project_root: ''
project_version: 1.0.0
rules:
  code_quality:
    enforce_docstrings: true
    max_file_length: 1000
    max_function_length: 50
    max_line_length: 120
    require_type_hints: true
  compliance:
    dependency_audit: true
    license_check: false
    vulnerability_scan: true
  security:
    require_https: false
    sanitize_outputs: true
    scan_for_secrets: true
    validate_inputs: true
  validation:
    allow_empty_files: true
    enforce_naming_conventions: true
    require_documentation: true
    strict_mode: false
structure_check:
  allowed_hidden_items:
  - .env
  - .env.example
  - .gitignore
  - .dockerignore
  - .eslintrc.js
  - .prettierrc
  - .pre-commit-config.yaml
  - .devcontainer
  - .github
  - .venv
  default_forbidden_patterns:
  - '*.tmp'
  - '*.bak'
  - '*.swp'
  - '*.log'
  - '*~'
  - Thumbs.db
  - .DS_Store
  - Everything.db
  - '*.db'
  - '*.sqlite'
  default_naming_rules:
    config: ^[a-zA-Z0-9_-]+\.(json|yaml|yml|ini|conf)$
    docs: ^[一-龥a-zA-Z0-9_ -]+\.(md|txt)$
    tools: ^[a-zA-Z0-9_-]+\.(py|js|sh|bat|ps1)$
  excluded_dirs:
  - .git
  - node_modules
  - __pycache__
  - .pytest_cache
  - venv
  - .venv
  - env
  - .env
  - dist
  - build
  - .idea
  - .vscode
  - .DS_Store
  - Thumbs.db
  excluded_dirs_for_redundancy:
  - bak
  - logs
  excluded_files:
  - .DS_Store
  - Thumbs.db
  - '*.pyc'
  - '*.pyo'
  - '*.pyd'
  - .gitkeep
  - .keep
  - '*.tmp'
  - '*.temp'
  - '*.log'
  generator:
    allowed_hidden_items:
    - .env
    - .env.example
    - .gitignore
    - .dockerignore
    - .eslintrc.js
    - .prettierrc
    - .pre-commit-config.yaml
    - .devcontainer
    - .github
    - .venv
    cache:
      cache_dir: .cache/structure
      cache_file: structure_cache.json
      check_mtime: true
      enabled: true
      ttl_hours: 24
    excluded_dirs:
    - __pycache__
    - .git
    - .vscode
    - .idea
    - node_modules
    - .pytest_cache
    - .coverage
    - htmlcov
    - dist
    - build
    - '*.egg-info'
    - .tox
    - .mypy_cache
    - .DS_Store
    - Thumbs.db
    - .venv
    - venv
    - env
    excluded_files:
    - .gitkeep
    - .DS_Store
    - Thumbs.db
    - '*.pyc'
    - '*.pyo'
    - '*.pyd'
    - __pycache__
    - '*.so'
    - '*.dylib'
    - '*.dll'
    - '*.tmp'
    - '*.temp'
    - '*.log'
    output_formats:
    - markdown
    - json
    performance:
      batch_size: 100
      enable_async: false
      max_workers: 4
    special_dirs:
      bak:
      - github_repo
      - 迁移备份
      - 专项备份
      - 待清理资料
      - 常规备份
      logs:
      - 工作记录
      - 检查报告
      - 其他日志
      - archive
  max_depth: 10
  report_dir: logs/检查报告
  report_name_format: 目录结构检查报告_{timestamp}.md
  root_directory_rules:
    allowed_directories:
    - bak
    - docs
    - logs
    - project
    - tools
    forbidden_directory_patterns:
    - config*
    - example*
    - sample*
    - temp*
    - tmp*
    - cache*
    - test*
    forbidden_file_patterns:
    - '*.db'
    - '*.sqlite'
    - Everything.db
    - '*.log'
    - '*.tmp'
  skip_deep_nested_dirs: true
  special_dirs:
    bak:
    - github_repo
    - 迁移备份
    - 专项备份
    - 待清理资料
    - 常规备份
    logs:
    - 工作记录
    - 检查报告
    - 其他日志
    - archive
  standard_list_file: docs/01-设计/目录结构标准清单.md
template:
  default_description: 3AI电器实业有限公司研发管理项目
  default_project_name: PG-PMC
  variables:
  - PROJECT_NAME
  - PROJECT_DESCRIPTION
  - CREATED_AT
  - UPDATED_AT
updated_at: '2025-07-26T23:06:29.517000'
